STRINGS = {
    "welcome": "👋 Welcome to <b>LinkUp</b> — a dating bot!\n\nFind interesting people near you.\n\n/start — begin\n/help — help",
    "already_registered": "✅ You're already registered! Use the menu below.",
    "register_start": "📝 Let's create your profile!\n\nWhat's your name?",
    "ask_age": "🎂 How old are you?",
    "ask_gender": "👤 Select your gender:",
    "ask_city": "🏙 Enter your city.\n\nSend your <b>location</b> 📍 or type your city name:",
    "ask_bio": "📖 Tell us about yourself (up to 500 characters).\n\nOr press «Skip»:",
    "ask_photos": "📸 Add up to 3 photos.\n\nSend photos one by one. Press «Done» when finished:",
    "registration_complete": "🎉 Profile created! Welcome to LinkUp!\n\nUse the menu to navigate.",
    "invalid_name": "❌ Name must be 1–100 characters. Try again:",
    "invalid_age": "❌ Age must be a number between 11 and 120. Try again:",
    "invalid_bio": "❌ Bio must not exceed 500 characters. Current: {count}. Try again:",
    "invalid_city": "❌ Could not find the city. Try a different name:",
    "max_photos": "❌ Maximum 3 photos. Press «Done».",
    "photo_added": "✅ Photo added ({count}/3).",
    "gender_male": "♂️ Male",
    "gender_female": "♀️ Female",
    "gender_other": "⚧ Other",
    "btn_skip": "Skip",
    "btn_done": "✅ Done",
    "btn_cancel": "❌ Cancel",
    "btn_back": "◀️ Back",
    "btn_yes": "✅ Yes",
    "btn_no": "❌ No",
    "main_menu": "🏠 Main Menu",
    "btn_search": "🔍 Search",
    "btn_profile": "👤 My Profile",
    "btn_likes": "❤️ Likes",
    "btn_matches": "💑 Matches",
    "btn_premium": "⭐ Premium",
    "btn_crystals": "💎 Crystals",
    "btn_settings": "⚙️ Settings",
    "btn_referral": "🔗 Referral Program",
    "btn_help": "❓ Help",
    "profile_view": "👤 <b>{name}</b>, {age} years old\n🏙 {city}\n{bio_line}\n\n{'⭐ Premium' if premium else ''}",
    "profile_no_bio": "No description",
    "profile_edit_menu": "✏️ What do you want to edit?",
    "btn_edit_name": "📝 Name",
    "btn_edit_age": "🎂 Age",
    "btn_edit_gender": "👤 Gender",
    "btn_edit_city": "🏙 City",
    "btn_edit_bio": "📖 About",
    "btn_edit_photos": "📸 Photos",
    "btn_edit_voice": "🎙 Voice",
    "btn_edit_filters": "🔍 Search Filters",
    "btn_delete_profile": "🗑 Delete Profile",
    "ask_new_name": "Enter new name:",
    "ask_new_age": "Enter new age:",
    "ask_new_bio": "Enter new description (up to 500 characters):",
    "ask_new_city": "Enter new city or send location:",
    "ask_new_voice": "🎙 Send a voice message:",
    "profile_updated": "✅ Profile updated!",
    "search_no_candidates": "😔 No one found with your filters. Try expanding your search criteria.",
    "search_profile": "👤 <b>{name}</b>, {age} years old\n🏙 {city}\n📏 {distance}\n{bio_line}\n\n{'⭐ Premium' if premium else ''}",
    "distance_km": "~{dist:.0f} km",
    "distance_same_city": "Your city",
    "distance_unknown": "Distance unknown",
    "btn_like": "❤️ Like",
    "btn_dislike": "👎 Pass",
    "btn_report": "🚨 Report",
    "btn_super_like": "💫 Super Like",
    "its_a_match": "🎉 <b>It's a Match!</b>\n\nYou and <b>{name}</b> liked each other!\n\n{link}",
    "match_notification": "💑 You have a new match with <b>{name}</b>!\n\n{link}",
    "like_sent": "❤️ Like sent!",
    "dislike_sent": "👎 Loading next profile...",
    "already_liked": "❌ You've already rated this profile.",
    "likes_list": "❤️ <b>Who you liked:</b>\n\nTotal: {count}",
    "matches_list": "💑 <b>Your matches:</b>\n\nTotal: {count}",
    "no_likes": "You haven't liked anyone yet.",
    "no_matches": "You have no matches yet.",
    "report_reason_title": "🚨 Reason for report:",
    "btn_report_spam": "📨 Spam",
    "btn_report_fake": "🎭 Fake",
    "btn_report_insults": "🤬 Insults",
    "btn_report_content": "🔞 Content",
    "btn_report_other": "❓ Other",
    "ask_report_comment": "Add a comment (optional):",
    "report_sent": "✅ Report submitted. Thank you!",
    "report_already_sent": "⚠️ You have already reported this user.",
    "premium_menu": "⭐ <b>Premium Status</b>\n\nPremium features:\n• Your profile shown 3× more often\n• ⭐ badge in profile\n\n{status}",
    "premium_active": "✅ Your Premium is active until: {date}",
    "premium_inactive": "❌ Premium is not active",
    "btn_premium_1m": "1 month — {stars}⭐ / {crystals}💎",
    "btn_premium_1y": "1 year — {stars}⭐ / {crystals}💎",
    "btn_buy_stars": "⭐ Buy with Stars",
    "btn_buy_crystals": "💎 Buy with Crystals",
    "btn_buy_card": "💳 Buy with Card",
    "premium_invoice_title": "⭐ LinkUp Premium",
    "premium_invoice_desc_1m": "1 month Premium access. Your profile shown 3× more often!",
    "premium_invoice_desc_1y": "1 year Premium access. Your profile shown 3× more often!",
    "premium_activated": "🎉 Premium activated until {date}! Your profile is now shown 3× more often!",
    "not_enough_crystals": "❌ Not enough crystals. You have: {balance}💎, needed: {needed}💎",
    "crystals_menu": "💎 <b>Crystals</b>\n\nBalance: <b>{balance}💎</b>\n\n1 ⭐ Star = 1 💎 Crystal",
    "btn_buy_crystals_10": "10💎 — 10⭐",
    "btn_buy_crystals_50": "50💎 — 50⭐",
    "btn_buy_crystals_100": "100💎 — 100⭐",
    "btn_crystals_history": "📋 Transaction History",
    "crystals_bought": "✅ Bought {amount}💎 crystals!\nBalance: {balance}💎",
    "crystals_history_title": "📋 <b>Crystal History:</b>\n\n",
    "crystals_history_item": "{date} | {sign}{amount}💎 | {reason} | Balance: {balance}💎\n",
    "no_history": "History is empty.",
    "filters_menu": "🔍 <b>Search Filters:</b>\n\nGender: {gender}\nAge: {age_min}–{age_max}\nDistance: {distance}",
    "filter_gender_any": "Any",
    "filter_distance_any": "Any",
    "btn_filter_gender": "👤 Search Gender",
    "btn_filter_age": "🎂 Age Range",
    "btn_filter_distance": "📏 Distance (km)",
    "ask_filter_age_min": "Enter minimum age (11-120):",
    "ask_filter_age_max": "Enter maximum age (11-120):",
    "ask_filter_distance": "Enter max distance in km (or 0 = no limit):",
    "filter_updated": "✅ Filter updated!",
    "settings_menu": "⚙️ <b>Settings</b>",
    "btn_lang": "🌍 Language",
    "language_changed": "✅ Language changed!",
    "choose_language": "🌍 Choose language:",
    "referral_menu": "🔗 <b>Referral Program</b>\n\nYour code: <code>{code}</code>\nInvited: {count} people\n\nFor each invited user you get <b>5💎</b>\n\nYour link:\n{link}",
    "referral_bonus_received": "🎁 You received {crystals}💎 for inviting a new user!",
    "referral_welcome": "🎁 You joined via a referral link! Welcome!",
    "help_text": "❓ <b>Help</b>\n\n/start — main menu\n/profile — my profile\n/search — search\n/premium — Premium\n/crystals — Crystals\n/referral — Referrals\n/settings — Settings\n/help — help\n\n🔞 Minimum age: 11\n📧 Support: @support",
    "banned_message": "🚫 Your account is banned. Contact support.",
    "throttle_message": "⏳ Please slow down. Wait a moment.",
    "error_occurred": "❌ An error occurred. Please try again later.",
    "profile_deactivated": "✅ Your profile is deactivated. You can create a new one with /start.",
    "confirm_delete_profile": "⚠️ Are you sure you want to delete your profile? All data will be removed.",
    "photos_menu": "📸 <b>Your Photos:</b>\n\nPhotos {count}/3",
    "btn_add_photo": "➕ Add Photo",
    "btn_delete_photo": "🗑 Delete Photo",
    "ask_which_photo_delete": "Enter photo number to delete (1, 2 or 3):",
    "photo_deleted": "✅ Photo #{num} deleted.",
    "no_photos": "No photos added.",
    "photo_not_found": "❌ Photo #{num} not found.",
    "voice_saved": "✅ Voice message saved!",
    "voice_deleted": "✅ Voice message deleted.",
    "btn_delete_voice": "🗑 Delete Voice",
    "admin_login": "🔐 Enter admin password:",
    "admin_wrong_password": "❌ Wrong password.",
    "admin_welcome": "👑 <b>Admin Panel</b>\n\nStats:\n👥 Users: {total}\n✅ Active: {active}\n⭐ Premium: {premium}\n🚫 Banned: {banned}\n📅 Today: {today}\n\n📋 Pending reports: {reports}",
    "admin_btn_stats": "📊 Statistics",
    "admin_btn_find_user": "🔍 Find User",
    "admin_btn_reports": "🚨 Reports",
    "admin_btn_ban": "🚫 Ban",
    "admin_btn_unban": "✅ Unban",
    "admin_btn_warn": "⚠️ Warn",
    "admin_btn_remove_warn": "↩️ Remove Warn",
    "admin_btn_delete_profile": "🗑 Delete Profile",
    "admin_ask_user": "Enter Telegram ID or username:",
    "admin_user_not_found": "❌ User not found.",
    "admin_user_info": "👤 <b>User:</b>\nID: {tg_id}\nName: {name}\nAge: {age}\nCity: {city}\nPremium: {premium}\nBanned: {banned}\nWarnings: {warns}/3\nRegistered: {created}",
    "admin_banned_user": "🚫 User {tg_id} banned.",
    "admin_unbanned_user": "✅ User {tg_id} unbanned.",
    "admin_warned_user": "⚠️ User {tg_id} warned ({warns}/3).",
    "admin_autoban": "🚫 User {tg_id} auto-banned (3/3 warnings).",
    "admin_warn_removed": "✅ Warning removed. Now: {warns}/3.",
    "admin_profile_deleted": "🗑 Profile of user {tg_id} deleted.",
    "admin_reports_list": "🚨 <b>Reports ({count}):</b>\n\n",
    "admin_report_item": "#{id} | from {reporter} to {reported}\nReason: {reason}\nComment: {comment}\n🕐 {date}\n\n",
    "admin_no_reports": "✅ No pending reports.",
    "admin_report_reviewed": "✅ Report #{id} marked as reviewed.",
    "admin_ask_ban_reason": "Enter ban reason (or skip):",
    "user_banned_notification": "🚫 Your account has been banned by an admin.\nReason: {reason}",
    "user_unbanned_notification": "✅ Your account has been unbanned.",
    "user_warned_notification": "⚠️ You received a warning ({warns}/3). After 3 warnings your account will be banned.",
    "user_autoban_notification": "🚫 Your account has been banned due to 3 warnings.",
    "no_profile": "❌ Profile not found. Use /start to register.",
    "profile_deactivated_msg": "❌ Your profile is deactivated. Activate it in profile settings.",
    "btn_activate_profile": "✅ Activate Profile",
    "profile_activated": "✅ Profile activated!",
    "user_link_username": "💬 <a href='https://t.me/{username}'>Message on Telegram</a>",
    "user_link_id": "💬 <a href='tg://user?id={user_id}'>Message on Telegram</a>",
    "payment_error": "❌ Payment error. Please try again later.",
    "invoice_label_premium_1m": "Premium 1 month",
    "invoice_label_premium_1y": "Premium 1 year",
    "invoice_label_crystals": "{amount} crystals",
    "btn_menu": "🏠 Menu",
}
