STRINGS = {
    "welcome": "👋 Добро пожаловать в <b>LinkUp</b> — бот знакомств!\n\nЗдесь вы найдёте интересных людей рядом с вами.\n\n/start — начать\n/help — помощь",
    "already_registered": "✅ Вы уже зарегистрированы! Используйте меню ниже.",
    "register_start": "📝 Давайте создадим ваш профиль!\n\nКак вас зовут?",
    "ask_age": "🎂 Сколько вам лет?",
    "ask_gender": "👤 Укажите ваш пол:",
    "ask_city": "🏙 Укажите ваш город.\n\nОтправьте <b>геолокацию</b> 📍 или напишите название города:",
    "ask_bio": "📖 Расскажите о себе (до 500 символов).\n\nИли нажмите «Пропустить»:",
    "ask_photos": "📸 Добавьте до 3 фотографий.\n\nОтправляйте фото по одному. Нажмите «Готово» когда закончите:",
    "registration_complete": "🎉 Профиль создан! Добро пожаловать в LinkUp!\n\nИспользуйте меню для навигации.",
    "invalid_name": "❌ Имя должно содержать от 1 до 100 символов. Попробуйте ещё раз:",
    "invalid_age": "❌ Возраст должен быть числом от 11 до 120. Попробуйте ещё раз:",
    "invalid_bio": "❌ Описание не должно превышать 500 символов. Сейчас: {count}. Попробуйте ещё раз:",
    "invalid_city": "❌ Не удалось определить город. Попробуйте ввести другое название:",
    "max_photos": "❌ Максимум 3 фотографии. Нажмите «Готово».",
    "photo_added": "✅ Фото добавлено ({count}/3).",
    "gender_male": "♂️ Мужской",
    "gender_female": "♀️ Женский",
    "gender_other": "⚧ Другой",
    "btn_skip": "Пропустить",
    "btn_done": "✅ Готово",
    "btn_cancel": "❌ Отмена",
    "btn_back": "◀️ Назад",
    "btn_yes": "✅ Да",
    "btn_no": "❌ Нет",
    "main_menu": "🏠 Главное меню",
    "btn_search": "🔍 Искать",
    "btn_profile": "👤 Мой профиль",
    "btn_likes": "❤️ Лайки",
    "btn_matches": "💑 Совпадения",
    "btn_premium": "⭐ Premium",
    "btn_crystals": "💎 Кристаллы",
    "btn_settings": "⚙️ Настройки",
    "btn_referral": "🔗 Реферальная программа",
    "btn_help": "❓ Помощь",
    "profile_view": "👤 <b>{name}</b>, {age} лет\n🏙 {city}\n{bio_line}\n\n{'⭐ Premium' if premium else ''}",
    "profile_no_bio": "Нет описания",
    "profile_edit_menu": "✏️ Что вы хотите изменить?",
    "btn_edit_name": "📝 Имя",
    "btn_edit_age": "🎂 Возраст",
    "btn_edit_gender": "👤 Пол",
    "btn_edit_city": "🏙 Город",
    "btn_edit_bio": "📖 О себе",
    "btn_edit_photos": "📸 Фото",
    "btn_edit_voice": "🎙 Голосовое",
    "btn_edit_filters": "🔍 Фильтры поиска",
    "btn_delete_profile": "🗑 Удалить анкету",
    "ask_new_name": "Введите новое имя:",
    "ask_new_age": "Введите новый возраст:",
    "ask_new_bio": "Введите новое описание (до 500 символов):",
    "ask_new_city": "Введите новый город или отправьте геолокацию:",
    "ask_new_voice": "🎙 Отправьте голосовое сообщение:",
    "profile_updated": "✅ Профиль обновлён!",
    "search_no_candidates": "😔 По вашим фильтрам никого не найдено. Попробуйте расширить критерии поиска.",
    "search_profile": "👤 <b>{name}</b>, {age} лет\n🏙 {city}\n📏 {distance}\n{bio_line}\n\n{'⭐ Premium' if premium else ''}",
    "distance_km": "~{dist:.0f} км",
    "distance_same_city": "Ваш город",
    "distance_unknown": "Расстояние неизвестно",
    "btn_like": "❤️ Нравится",
    "btn_dislike": "👎 Дальше",
    "btn_report": "🚨 Пожаловаться",
    "btn_super_like": "💫 Суперлайк",
    "its_a_match": "🎉 <b>Это мэтч!</b>\n\nВы и <b>{name}</b> понравились друг другу!\n\n{link}",
    "match_notification": "💑 У вас новый мэтч с <b>{name}</b>!\n\n{link}",
    "like_sent": "❤️ Лайк отправлен!",
    "dislike_sent": "👎 Показываем следующую анкету...",
    "already_liked": "❌ Вы уже оценивали эту анкету.",
    "likes_list": "❤️ <b>Кому вы поставили лайки:</b>\n\nВсего: {count}",
    "matches_list": "💑 <b>Ваши мэтчи:</b>\n\nВсего: {count}",
    "no_likes": "У вас пока нет лайков.",
    "no_matches": "У вас пока нет мэтчей.",
    "report_reason_title": "🚨 Причина жалобы:",
    "btn_report_spam": "📨 Спам",
    "btn_report_fake": "🎭 Фейк",
    "btn_report_insults": "🤬 Оскорбления",
    "btn_report_content": "🔞 Контент",
    "btn_report_other": "❓ Другое",
    "ask_report_comment": "Добавьте комментарий (необязательно):",
    "report_sent": "✅ Жалоба отправлена. Спасибо!",
    "report_already_sent": "⚠️ Вы уже отправляли жалобу на этого пользователя.",
    "premium_menu": "⭐ <b>Premium-статус</b>\n\nPremium даёт:\n• Ваша анкета показывается в 3× чаще\n• Значок ⭐ в профиле\n\n{status}",
    "premium_active": "✅ Ваш Premium активен до: {date}",
    "premium_inactive": "❌ Premium не активен",
    "btn_premium_1m": "1 месяц — {stars}⭐ / {crystals}💎",
    "btn_premium_1y": "1 год — {stars}⭐ / {crystals}💎",
    "btn_buy_stars": "⭐ Купить за Stars",
    "btn_buy_crystals": "💎 Купить за кристаллы",
    "btn_buy_card": "💳 Купить за карту",
    "premium_invoice_title": "⭐ LinkUp Premium",
    "premium_invoice_desc_1m": "Доступ к Premium на 1 месяц. Ваша анкета показывается в 3× чаще!",
    "premium_invoice_desc_1y": "Доступ к Premium на 1 год. Ваша анкета показывается в 3× чаще!",
    "premium_activated": "🎉 Premium активирован до {date}! Ваша анкета теперь показывается в 3× чаще!",
    "not_enough_crystals": "❌ Недостаточно кристаллов. У вас: {balance}💎, нужно: {needed}💎",
    "crystals_menu": "💎 <b>Кристаллы</b>\n\nБаланс: <b>{balance}💎</b>\n\n1 ⭐ Star = 1 💎 Кристалл",
    "btn_buy_crystals_10": "10💎 — 10⭐",
    "btn_buy_crystals_50": "50💎 — 50⭐",
    "btn_buy_crystals_100": "100💎 — 100⭐",
    "btn_crystals_history": "📋 История транзакций",
    "crystals_bought": "✅ Куплено {amount}💎 кристаллов!\nБаланс: {balance}💎",
    "crystals_history_title": "📋 <b>История кристаллов:</b>\n\n",
    "crystals_history_item": "{date} | {sign}{amount}💎 | {reason} | Баланс: {balance}💎\n",
    "no_history": "История пуста.",
    "filters_menu": "🔍 <b>Фильтры поиска:</b>\n\nПол: {gender}\nВозраст: {age_min}–{age_max}\nРасстояние: {distance}",
    "filter_gender_any": "Любой",
    "filter_distance_any": "Любое",
    "btn_filter_gender": "👤 Пол поиска",
    "btn_filter_age": "🎂 Возраст",
    "btn_filter_distance": "📏 Расстояние (км)",
    "ask_filter_age_min": "Введите минимальный возраст (11-120):",
    "ask_filter_age_max": "Введите максимальный возраст (11-120):",
    "ask_filter_distance": "Введите максимальное расстояние в км (или 0 = без ограничений):",
    "filter_updated": "✅ Фильтр обновлён!",
    "settings_menu": "⚙️ <b>Настройки</b>",
    "btn_lang": "🌍 Язык",
    "language_changed": "✅ Язык изменён!",
    "choose_language": "🌍 Выберите язык:",
    "referral_menu": "🔗 <b>Реферальная программа</b>\n\nВаш код: <code>{code}</code>\nПриглашено: {count} чел.\n\nЗа каждого приглашённого вы получаете <b>5💎</b>\n\nВаша ссылка:\n{link}",
    "referral_bonus_received": "🎁 Вы получили {crystals}💎 за приглашение нового пользователя!",
    "referral_welcome": "🎁 Вы пришли по реферальной ссылке! Добро пожаловать!",
    "help_text": "❓ <b>Помощь</b>\n\n/start — главное меню\n/profile — мой профиль\n/search — поиск\n/premium — Premium\n/crystals — Кристаллы\n/referral — Рефералы\n/settings — Настройки\n/help — помощь\n\n🔞 Возраст для регистрации: от 11 лет\n📧 Поддержка: @support",
    "banned_message": "🚫 Ваш аккаунт заблокирован. Обратитесь в поддержку.",
    "throttle_message": "⏳ Пожалуйста, не спешите. Подождите немного.",
    "error_occurred": "❌ Произошла ошибка. Попробуйте позже.",
    "profile_deactivated": "✅ Ваша анкета деактивирована. Вы можете создать новую командой /start.",
    "confirm_delete_profile": "⚠️ Вы уверены, что хотите удалить анкету? Все данные будут удалены.",
    "photos_menu": "📸 <b>Ваши фото:</b>\n\nФото {count}/3",
    "btn_add_photo": "➕ Добавить фото",
    "btn_delete_photo": "🗑 Удалить фото",
    "ask_which_photo_delete": "Введите номер фото для удаления (1, 2 или 3):",
    "photo_deleted": "✅ Фото #{num} удалено.",
    "no_photos": "Фото не добавлены.",
    "photo_not_found": "❌ Фото #{num} не найдено.",
    "voice_saved": "✅ Голосовое сообщение сохранено!",
    "voice_deleted": "✅ Голосовое сообщение удалено.",
    "btn_delete_voice": "🗑 Удалить голосовое",
    "admin_login": "🔐 Введите пароль администратора:",
    "admin_wrong_password": "❌ Неверный пароль.",
    "admin_welcome": "👑 <b>Панель администратора</b>\n\nСтатистика:\n👥 Пользователи: {total}\n✅ Активных: {active}\n⭐ Premium: {premium}\n🚫 Забанено: {banned}\n📅 Сегодня: {today}\n\n📋 Жалоб ожидает: {reports}",
    "admin_btn_stats": "📊 Статистика",
    "admin_btn_find_user": "🔍 Найти пользователя",
    "admin_btn_reports": "🚨 Жалобы",
    "admin_btn_ban": "🚫 Забанить",
    "admin_btn_unban": "✅ Разбанить",
    "admin_btn_warn": "⚠️ Варн",
    "admin_btn_remove_warn": "↩️ Снять варн",
    "admin_btn_delete_profile": "🗑 Удалить анкету",
    "admin_ask_user": "Введите Telegram ID или имя пользователя:",
    "admin_user_not_found": "❌ Пользователь не найден.",
    "admin_user_info": "👤 <b>Пользователь:</b>\nID: {tg_id}\nИмя: {name}\nВозраст: {age}\nГород: {city}\nPremium: {premium}\nЗабанен: {banned}\nПредупреждений: {warns}/3\nРегистрация: {created}",
    "admin_banned_user": "🚫 Пользователь {tg_id} заблокирован.",
    "admin_unbanned_user": "✅ Пользователь {tg_id} разблокирован.",
    "admin_warned_user": "⚠️ Пользователь {tg_id} получил предупреждение ({warns}/3).",
    "admin_autoban": "🚫 Пользователь {tg_id} автоматически забанен (3/3 предупреждения).",
    "admin_warn_removed": "✅ Предупреждение снято. Теперь: {warns}/3.",
    "admin_profile_deleted": "🗑 Анкета пользователя {tg_id} удалена.",
    "admin_reports_list": "🚨 <b>Жалобы ({count}):</b>\n\n",
    "admin_report_item": "#{id} | от {reporter} на {reported}\nПричина: {reason}\nКомментарий: {comment}\n🕐 {date}\n\n",
    "admin_no_reports": "✅ Нет непросмотренных жалоб.",
    "admin_report_reviewed": "✅ Жалоба #{id} отмечена как просмотренная.",
    "admin_ask_ban_reason": "Укажите причину бана (или пропустите):",
    "user_banned_notification": "🚫 Ваш аккаунт заблокирован администратором.\nПричина: {reason}",
    "user_unbanned_notification": "✅ Ваш аккаунт разблокирован.",
    "user_warned_notification": "⚠️ Вы получили предупреждение ({warns}/3). При 3 предупреждениях аккаунт будет заблокирован.",
    "user_autoban_notification": "🚫 Ваш аккаунт заблокирован из-за 3 предупреждений.",
    "no_profile": "❌ Профиль не найден. Используйте /start для регистрации.",
    "profile_deactivated_msg": "❌ Ваша анкета деактивирована. Активируйте её в настройках профиля.",
    "btn_activate_profile": "✅ Активировать анкету",
    "profile_activated": "✅ Анкета активирована!",
    "user_link_username": "💬 <a href='https://t.me/{username}'>Написать в Telegram</a>",
    "user_link_id": "💬 <a href='tg://user?id={user_id}'>Написать в Telegram</a>",
    "payment_error": "❌ Ошибка оплаты. Попробуйте позже.",
    "invoice_label_premium_1m": "Premium 1 месяц",
    "invoice_label_premium_1y": "Premium 1 год",
    "invoice_label_crystals": "{amount} кристаллов",
    "btn_menu": "🏠 Меню",
}
