STRINGS = {
    "welcome": "👋 欢迎来到 <b>LinkUp</b> — 交友机器人！\n\n在这里找到你身边有趣的人。\n\n/start — 开始\n/help — 帮助",
    "already_registered": "✅ 您已经注册了！请使用下方菜单。",
    "register_start": "📝 让我们创建您的个人资料！\n\n您叫什么名字？",
    "ask_age": "🎂 您多少岁了？",
    "ask_gender": "👤 请选择您的性别：",
    "ask_city": "🏙 请输入您的城市。\n\n发送您的<b>位置</b>📍或输入城市名称：",
    "ask_bio": "📖 介绍一下自己（最多500字）。\n\n或者按「跳过」：",
    "ask_photos": "📸 添加最多3张照片。\n\n逐张发送照片。完成后按「完成」：",
    "registration_complete": "🎉 个人资料已创建！欢迎来到LinkUp！\n\n使用菜单进行导航。",
    "invalid_name": "❌ 名字必须在1-100个字符之间。请重试：",
    "invalid_age": "❌ 年龄必须在11到120之间。请重试：",
    "invalid_bio": "❌ 简介不能超过500个字符。当前：{count}。请重试：",
    "invalid_city": "❌ 无法找到该城市。请尝试其他名称：",
    "max_photos": "❌ 最多3张照片。按「完成」。",
    "photo_added": "✅ 照片已添加（{count}/3）。",
    "gender_male": "♂️ 男",
    "gender_female": "♀️ 女",
    "gender_other": "⚧ 其他",
    "btn_skip": "跳过",
    "btn_done": "✅ 完成",
    "btn_cancel": "❌ 取消",
    "btn_back": "◀️ 返回",
    "btn_yes": "✅ 是",
    "btn_no": "❌ 否",
    "main_menu": "🏠 主菜单",
    "btn_search": "🔍 搜索",
    "btn_profile": "👤 我的资料",
    "btn_likes": "❤️ 喜欢",
    "btn_matches": "💑 匹配",
    "btn_premium": "⭐ 高级",
    "btn_crystals": "💎 水晶",
    "btn_settings": "⚙️ 设置",
    "btn_referral": "🔗 推荐计划",
    "btn_help": "❓ 帮助",
    "profile_view": "👤 <b>{name}</b>，{age}岁\n🏙 {city}\n{bio_line}\n\n{'⭐ 高级会员' if premium else ''}",
    "profile_no_bio": "无描述",
    "profile_edit_menu": "✏️ 您想修改什么？",
    "btn_edit_name": "📝 姓名",
    "btn_edit_age": "🎂 年龄",
    "btn_edit_gender": "👤 性别",
    "btn_edit_city": "🏙 城市",
    "btn_edit_bio": "📖 关于我",
    "btn_edit_photos": "📸 照片",
    "btn_edit_voice": "🎙 语音",
    "btn_edit_filters": "🔍 搜索过滤器",
    "btn_delete_profile": "🗑 删除资料",
    "ask_new_name": "输入新名字：",
    "ask_new_age": "输入新年龄：",
    "ask_new_bio": "输入新简介（最多500字）：",
    "ask_new_city": "输入新城市或发送位置：",
    "ask_new_voice": "🎙 发送语音消息：",
    "profile_updated": "✅ 资料已更新！",
    "search_no_candidates": "😔 根据您的过滤条件未找到任何人。尝试扩大搜索条件。",
    "search_profile": "👤 <b>{name}</b>，{age}岁\n🏙 {city}\n📏 {distance}\n{bio_line}\n\n{'⭐ 高级' if premium else ''}",
    "distance_km": "约{dist:.0f}公里",
    "distance_same_city": "您的城市",
    "distance_unknown": "距离未知",
    "btn_like": "❤️ 喜欢",
    "btn_dislike": "👎 下一个",
    "btn_report": "🚨 举报",
    "btn_super_like": "💫 超级喜欢",
    "its_a_match": "🎉 <b>匹配成功！</b>\n\n您和<b>{name}</b>互相喜欢！\n\n{link}",
    "match_notification": "💑 您与<b>{name}</b>有新的匹配！\n\n{link}",
    "like_sent": "❤️ 已发送喜欢！",
    "dislike_sent": "👎 正在加载下一个资料...",
    "already_liked": "❌ 您已经评价过该资料。",
    "likes_list": "❤️ <b>您喜欢的人：</b>\n\n共计：{count}",
    "matches_list": "💑 <b>您的匹配：</b>\n\n共计：{count}",
    "no_likes": "您还没有喜欢任何人。",
    "no_matches": "您还没有匹配。",
    "report_reason_title": "🚨 举报原因：",
    "btn_report_spam": "📨 垃圾信息",
    "btn_report_fake": "🎭 虚假账号",
    "btn_report_insults": "🤬 侮辱",
    "btn_report_content": "🔞 内容",
    "btn_report_other": "❓ 其他",
    "ask_report_comment": "添加评论（可选）：",
    "report_sent": "✅ 举报已提交。感谢！",
    "report_already_sent": "⚠️ 您已经举报过该用户。",
    "premium_menu": "⭐ <b>高级状态</b>\n\n高级功能：\n• 您的资料显示频率高3倍\n• 资料中的⭐标志\n\n{status}",
    "premium_active": "✅ 您的高级会员有效期至：{date}",
    "premium_inactive": "❌ 高级会员未激活",
    "btn_premium_1m": "1个月 — {stars}⭐ / {crystals}💎",
    "btn_premium_1y": "1年 — {stars}⭐ / {crystals}💎",
    "btn_buy_stars": "⭐ 用Stars购买",
    "btn_buy_crystals": "💎 用水晶购买",
    "btn_buy_card": "💳 用银行卡购买",
    "premium_invoice_title": "⭐ LinkUp 高级会员",
    "premium_invoice_desc_1m": "1个月高级会员。您的资料显示频率高3倍！",
    "premium_invoice_desc_1y": "1年高级会员。您的资料显示频率高3倍！",
    "premium_activated": "🎉 高级会员已激活至{date}！您的资料现在显示频率高3倍！",
    "not_enough_crystals": "❌ 水晶不足。您有：{balance}💎，需要：{needed}💎",
    "crystals_menu": "💎 <b>水晶</b>\n\n余额：<b>{balance}💎</b>\n\n1 ⭐ Star = 1 💎 水晶",
    "btn_buy_crystals_10": "10💎 — 10⭐",
    "btn_buy_crystals_50": "50💎 — 50⭐",
    "btn_buy_crystals_100": "100💎 — 100⭐",
    "btn_crystals_history": "📋 交易记录",
    "crystals_bought": "✅ 购买了{amount}💎水晶！\n余额：{balance}💎",
    "crystals_history_title": "📋 <b>水晶记录：</b>\n\n",
    "crystals_history_item": "{date} | {sign}{amount}💎 | {reason} | 余额：{balance}💎\n",
    "no_history": "记录为空。",
    "filters_menu": "🔍 <b>搜索过滤器：</b>\n\n性别：{gender}\n年龄：{age_min}–{age_max}\n距离：{distance}",
    "filter_gender_any": "任意",
    "filter_distance_any": "任意",
    "btn_filter_gender": "👤 搜索性别",
    "btn_filter_age": "🎂 年龄范围",
    "btn_filter_distance": "📏 距离（公里）",
    "ask_filter_age_min": "输入最小年龄（11-120）：",
    "ask_filter_age_max": "输入最大年龄（11-120）：",
    "ask_filter_distance": "输入最大距离（公里）（或0=无限制）：",
    "filter_updated": "✅ 过滤器已更新！",
    "settings_menu": "⚙️ <b>设置</b>",
    "btn_lang": "🌍 语言",
    "language_changed": "✅ 语言已更改！",
    "choose_language": "🌍 选择语言：",
    "referral_menu": "🔗 <b>推荐计划</b>\n\n您的代码：<code>{code}</code>\n已邀请：{count}人\n\n每邀请一位用户获得<b>5💎</b>\n\n您的链接：\n{link}",
    "referral_bonus_received": "🎁 您获得了{crystals}💎，感谢邀请新用户！",
    "referral_welcome": "🎁 您通过推荐链接加入！欢迎！",
    "help_text": "❓ <b>帮助</b>\n\n/start — 主菜单\n/profile — 我的资料\n/search — 搜索\n/premium — 高级\n/crystals — 水晶\n/referral — 推荐\n/settings — 设置\n/help — 帮助\n\n🔞 最低注册年龄：11岁\n📧 支持：@support",
    "banned_message": "🚫 您的账号已被封禁。请联系客服。",
    "throttle_message": "⏳ 请不要太快。稍等片刻。",
    "error_occurred": "❌ 发生错误。请稍后再试。",
    "profile_deactivated": "✅ 您的资料已停用。您可以使用/start创建新资料。",
    "confirm_delete_profile": "⚠️ 确定要删除您的资料吗？所有数据将被删除。",
    "photos_menu": "📸 <b>您的照片：</b>\n\n照片{count}/3",
    "btn_add_photo": "➕ 添加照片",
    "btn_delete_photo": "🗑 删除照片",
    "ask_which_photo_delete": "输入要删除的照片编号（1、2或3）：",
    "photo_deleted": "✅ 照片#{num}已删除。",
    "no_photos": "未添加照片。",
    "photo_not_found": "❌ 照片#{num}未找到。",
    "voice_saved": "✅ 语音消息已保存！",
    "voice_deleted": "✅ 语音消息已删除。",
    "btn_delete_voice": "🗑 删除语音",
    "admin_login": "🔐 输入管理员密码：",
    "admin_wrong_password": "❌ 密码错误。",
    "admin_welcome": "👑 <b>管理员面板</b>\n\n统计：\n👥 用户：{total}\n✅ 活跃：{active}\n⭐ 高级：{premium}\n🚫 封禁：{banned}\n📅 今天：{today}\n\n📋 待处理举报：{reports}",
    "admin_btn_stats": "📊 统计",
    "admin_btn_find_user": "🔍 查找用户",
    "admin_btn_reports": "🚨 举报",
    "admin_btn_ban": "🚫 封禁",
    "admin_btn_unban": "✅ 解封",
    "admin_btn_warn": "⚠️ 警告",
    "admin_btn_remove_warn": "↩️ 撤销警告",
    "admin_btn_delete_profile": "🗑 删除资料",
    "admin_ask_user": "输入Telegram ID或用户名：",
    "admin_user_not_found": "❌ 未找到用户。",
    "admin_user_info": "👤 <b>用户：</b>\nID：{tg_id}\n姓名：{name}\n年龄：{age}\n城市：{city}\n高级：{premium}\n封禁：{banned}\n警告：{warns}/3\n注册：{created}",
    "admin_banned_user": "🚫 用户{tg_id}已封禁。",
    "admin_unbanned_user": "✅ 用户{tg_id}已解封。",
    "admin_warned_user": "⚠️ 用户{tg_id}已警告（{warns}/3）。",
    "admin_autoban": "🚫 用户{tg_id}已自动封禁（3/3警告）。",
    "admin_warn_removed": "✅ 警告已撤销。当前：{warns}/3。",
    "admin_profile_deleted": "🗑 用户{tg_id}的资料已删除。",
    "admin_reports_list": "🚨 <b>举报（{count}）：</b>\n\n",
    "admin_report_item": "#{id} | 从{reporter}到{reported}\n原因：{reason}\n评论：{comment}\n🕐 {date}\n\n",
    "admin_no_reports": "✅ 没有待处理的举报。",
    "admin_report_reviewed": "✅ 举报#{id}已标记为已审核。",
    "admin_ask_ban_reason": "输入封禁原因（或跳过）：",
    "user_banned_notification": "🚫 您的账号已被管理员封禁。\n原因：{reason}",
    "user_unbanned_notification": "✅ 您的账号已解封。",
    "user_warned_notification": "⚠️ 您收到了一个警告（{warns}/3）。3次警告后账号将被封禁。",
    "user_autoban_notification": "🚫 您的账号因3次警告已被封禁。",
    "no_profile": "❌ 未找到资料。使用/start注册。",
    "profile_deactivated_msg": "❌ 您的资料已停用。在资料设置中激活。",
    "btn_activate_profile": "✅ 激活资料",
    "profile_activated": "✅ 资料已激活！",
    "user_link_username": "💬 <a href='https://t.me/{username}'>在Telegram上发送消息</a>",
    "user_link_id": "💬 <a href='tg://user?id={user_id}'>在Telegram上发送消息</a>",
    "payment_error": "❌ 支付错误。请稍后再试。",
    "invoice_label_premium_1m": "高级会员1个月",
    "invoice_label_premium_1y": "高级会员1年",
    "invoice_label_crystals": "{amount}水晶",
    "btn_menu": "🏠 菜单",
}
